version: '3.8'

services:
  hadoop:
    container_name: hadoop
    build:
      context: ./Hadoop/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Hadoop/map-reduce:/home/hduser/map-reduce
      #- ./Hadoop/buscador:/home/hduser/buscador
    ports:
      - 9864:9864
      - 9870:9870
      - 8088:8088
      - 9000:9000
      - 8020:8020