version: '3'
services:
  master:
    build:
      context: ./app/server
      dockerfile: Dockerfile
    container_name: master
    command: ["master", "50051"]
    tty: true
    stdin_open: true
    volumes:
      - './app/server:/app'
    ports:
      - "50051:50051"
    networks:
      - cache_network

  slave:
    build:
      context: ./app/server
      dockerfile: Dockerfile
    container_name: slave
    command: ["slave", "50051", "--master_ip", "master", "--master_port", "50051", "--service_name", "slave"]
    tty: true
    stdin_open: true
    volumes:
      - './app/server:/app'
      - './data_gen/cars.json:/app/cars.json'
    networks:
      - cache_network
    restart: always
    depends_on: 
      - master
  
  search:
    build:
      context: ./app/search
      dockerfile: Dockerfile
    container_name: search
    #command: ["slave", "50051", "--master_ip", "master", "--master_port", "50051"]
    tty: true
    stdin_open: true
    volumes:
      - './app/search:/app'
      - './data_gen/cars.json:/app/cars.json'
    networks:
      - cache_network
    restart: always
    depends_on: 
      - master

networks:
  cache_network: